[theme]
# Cor primária para elementos interativos (widgets, botões, etc.)
# Laranja que você escolheu
primaryColor="#243834"

# Cor de fundo principal do app (mantemos branco para clareza)
backgroundColor="#FFFFFF"

# Cor de fundo para a barra lateral e outros elementos secundários
secondaryBackgroundColor="#e97132"

# Cor do texto principal (verde escuro que você escolheu)
textColor="#e97132"

# Fonte padrão
font="sans serif"

[browser]
gatherUsageStats = false
toolbarMode = "minimal"
